#!/usr/bin/env expect

set env(HOME) /usr/local/bin
set env(SHELL) /bin/bash
set env(TERM) xterm
set timeout 3

# Plaintext password
set PASSWORD [lindex ${argv} 0]

# Destination User
set USER [lindex ${argv} 1]

# Destination IP address
set HOST [lindex ${argv} 2]

# Destination Port
set PORT [lindex ${argv} 3]

# Commands
set COMMAND [lindex ${argv} 4]

# Usage instructions if no arguments supplied.
if { ${argc} < 1 } {
	send_user "Usage: ${argv0} <password> <user> <host> <port> \[command\]\n"
	send_user "e.g.   ${argv0} password root 127.0.0.1 22 \"pwd\"\n"
	exit 1
}

if {
	[info exists HOST]
	&& "${HOST}" == ""
} {
	set HOST "127.0.0.1"
}

if {
	[info exists PORT]
	&& "${PORT}" == ""
} {
	set PORT "22"
}

if {
	[info exists USER]
	&& "${USER}" == ""
} {
	set USER "root"
}

if {
	[info exists COMMAND]
	&& "${COMMAND}" == ""
} {
	set COMMAND "pwd"
}

log_user 0
spawn sftp -q -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o PubkeyAuthentication=no -o Port=${PORT} ${USER}@${HOST}
expect {
	default {
		send_user "ERROR: Unable to connect to ${USER}@${HOST}:${PORT}\n"
		exit 1
	}
	"assword:" {
		send "${PASSWORD}\n"
		expect {
			default {
				log_user 1
				send "${COMMAND}\n"
			}
		}
		expect eof
	}
}