
SERVICE_UNIT_NAME=${SERVICE_UNIT_NAME:-ssh}
SERVICE_UNIT_GROUP=${SERVICE_UNIT_GROUP:-pool-1}
SERVICE_UNIT_LOCAL_ID=${SERVICE_UNIT_LOCAL_ID:-1}
SERVICE_UNIT_INSTANCE=${SERVICE_UNIT_INSTANCE:-1}
SERVICE_UNIT_INSTALL_TIMEOUT=${SERVICE_UNIT_INSTALL_TIMEOUT:-5}

SERVICE_UNIT_LONG_NAME=${SERVICE_UNIT_NAME}.${SERVICE_UNIT_GROUP}.${SERVICE_UNIT_LOCAL_ID}.${SERVICE_UNIT_INSTANCE}
SERVICE_UNIT_INSTALL_TEMPLATE_NAME=${DOCKER_IMAGE_NAME}@.service
SERVICE_UNIT_TEMPLATE_NAME=${SERVICE_UNIT_NAME}.${SERVICE_UNIT_GROUP}@.service
SERVICE_UNIT_INSTANCE_NAME=${SERVICE_UNIT_NAME}.${SERVICE_UNIT_GROUP}@${SERVICE_UNIT_LOCAL_ID}.${SERVICE_UNIT_INSTANCE}.service
SERVICE_UNIT_REGISTER_INSTALL_TEMPLATE_NAME=${DOCKER_IMAGE_NAME}.register@.service
SERVICE_UNIT_REGISTER_TEMPLATE_NAME=${SERVICE_UNIT_NAME}.${SERVICE_UNIT_GROUP}.register@.service
SERVICE_UNIT_REGISTER_INSTANCE_NAME=${SERVICE_UNIT_NAME}.${SERVICE_UNIT_GROUP}.register@${SERVICE_UNIT_LOCAL_ID}.${SERVICE_UNIT_INSTANCE}.service

SERVICE_UNIT_ENVIRONMENT_KEYS="
 DOCKER_CONTAINER_PARAMETERS_APPEND
 DOCKER_IMAGE_TAG
 DOCKER_PORT_MAP_TCP_22
 SSH_AUTHORIZED_KEYS
 SSH_AUTOSTART_SSHD
 SSH_AUTOSTART_SSHD_BOOTSTRAP
 SSH_CHROOT_DIRECTORY
 SSH_INHERIT_ENVIRONMENT
 SSH_SUDO
 SSH_USER
 SSH_USER_FORCE_SFTP
 SSH_USER_HOME
 SSH_USER_ID
 SSH_USER_PASSWORD
 SSH_USER_PASSWORD_HASHED
 SSH_USER_SHELL
"
