#!/usr/bin/env bash

set -e

function __cleanup ()
{
	__delete_lock
}

function __create_lock ()
{
	if [[ -n ${lock_file} ]]
	then
		touch "${lock_file}"
	fi
}

function __delete_lock ()
{
	if [[ -e ${lock_file} ]]
	then
		rm -f "${lock_file}"
	fi
}

function __get_options ()
{
	local -r options="${1}"

	printf -- \
		'-D -e -u 0%s%s' \
		"${options:+" "}" \
		"${options}"
}

function __get_enable_sshd_bootstrap ()
{
	local -r default_value="${1:-true}"

	local value="${ENABLE_SSHD_BOOTSTRAP}"

	if ! __is_valid_enable_sshd_bootstrap "${value}"
	then
		value="${default_value}"
	fi

	printf -- '%s' "${value}"
}

function __is_valid_enable_sshd_bootstrap ()
{
	local -r boolean_value='^(true|false)$'
	local -r value="${1}"

	if [[ ${value} =~ ${boolean_value} ]]
	then
		return 0
	fi

	return 1
}

function main ()
{
	local -r bin="/usr/sbin/sshd"
	local -r bootstrap_enabled="$(
		__get_enable_sshd_bootstrap
	)"
	local -r bootstrap_state_file="/var/lib/misc/sshd-bootstrap"
	local -r lock_file="/var/lock/subsys/sshd-wrapper"
	local -r nice="/bin/nice"
	local -r niceness="10"

	local options
	local verbose="false"

	# Parse options
	while [[ "${#}" -gt 0 ]]
	do
		case "${1}" in
			-v|--verbose)
				verbose="true"
				shift 1
				;;
		esac
	done

	if [[ -e ${lock_file} ]]
	then
		>&2 printf -- \
			'ERROR: %s lock detected - aborting\n' \
			"${0##*/}"
		exit 1
	fi

	trap __cleanup \
		EXIT INT TERM
	__create_lock

	options="$(
		__get_options
	)"

	if [[ ${bootstrap_enabled} == false ]]
	then
		# block.
		sleep infinity
	fi

	until [[ -e ${bootstrap_state_file} ]]
	do
		sleep 0.1
	done

	if [[ ${verbose} == true ]]
	then
		printf -- \
			'INFO: %s starting %s\n' \
			"${0##*/}" \
			"${bin##*/}"
	fi

	__cleanup
	trap - \
		EXIT INT TERM

	exec ${nice} \
		-n ${niceness} \
		${bin} \
		${options}
}

main "${@}"
